services:
  redis:
    image: redis:alpine
    ports:
     - 6379

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
     - 5432
